# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_seting.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon

from style import first_frame_black_stl, theme_set_black_stl, voice_set_black_stl, second_frame_black_stl
from style import set_cls_btn_black_stl, confirm_btn_black_stl, status_bar_black_stl

set_file = open('setings.txt')
set_value = [tuple(i.strip('\n').split('\t')) for i in open('setings.txt').readlines()]

voice = set_value[1][1]
class Ui_Seting_Black(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(417, 124)
        Dialog.setStyleSheet("background: #1C0460")
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(70, 30, 120, 51))
        self.frame.setStyleSheet(first_frame_black_stl)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.woman_radio_btn = QtWidgets.QRadioButton(self.frame)
        self.woman_radio_btn.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.woman_radio_btn.setObjectName("woman_radio_btn")
        self.human_radio_btn = QtWidgets.QRadioButton(self.frame)
        self.human_radio_btn.setGeometry(QtCore.QRect(10, 2, 91, 20))
        self.human_radio_btn.setObjectName("human_radio_btn")
        self.theme_set = QtWidgets.QLabel(Dialog)
        self.theme_set.setGeometry(QtCore.QRect(200, 30, 51, 21))
        self.theme_set.setStyleSheet(theme_set_black_stl)
        self.theme_set.setObjectName("theme_set")
        self.voice_set = QtWidgets.QLabel(Dialog)
        self.voice_set.setGeometry(QtCore.QRect(10, 30, 51, 21))
        self.voice_set.setStyleSheet(voice_set_black_stl)
        self.voice_set.setObjectName("voice_set")
        self.frame_2 = QtWidgets.QFrame(Dialog)
        self.frame_2.setGeometry(QtCore.QRect(260, 30, 120, 51))
        self.frame_2.setStyleSheet(second_frame_black_stl)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.white_set_btn = QtWidgets.QRadioButton(self.frame_2)
        self.white_set_btn.setGeometry(QtCore.QRect(10, 30, 101, 20))
        self.white_set_btn.setObjectName("white_set_btn")

        self.black_set_btn = QtWidgets.QRadioButton(self.frame_2)
        self.black_set_btn.setGeometry(QtCore.QRect(10, 2, 91, 20))
        self.black_set_btn.setObjectName("black_set_btn")
        self.black_set_btn.setChecked(True)
        self.set_exit_btn = QtWidgets.QPushButton(Dialog)
        self.set_exit_btn.setGeometry(QtCore.QRect(390, 10, 21, 23))
        self.set_exit_btn.setStyleSheet(set_cls_btn_black_stl)
        self.set_exit_btn.setObjectName("set_exit_btn")
        self.set_exit_btn.setIcon(QIcon('closer.png'))
        self.set_exit_btn.setIconSize(QSize(10, 10))
        self.confirm_btn = QtWidgets.QPushButton(Dialog)
        self.confirm_btn.setGeometry(QtCore.QRect(330, 90, 81, 23))
        self.confirm_btn.setStyleSheet(confirm_btn_black_stl)
        self.confirm_btn.setObjectName("confirm_btn")
        self.status_bar = QtWidgets.QLabel(Dialog)
        self.status_bar.setGeometry(QtCore.QRect(10, 93, 151, 20))
        self.status_bar.setStyleSheet(status_bar_black_stl)
        self.status_bar.setObjectName("status_bar")
        if voice == 'man':
            self.human_radio_btn.setChecked(True)
        elif voice == 'woman':
            self.woman_radio_btn.setChecked(True)
        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.buttonBox.accepted.connect(Dialog.accept)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Настройки"))
        self.woman_radio_btn.setText(_translate("Dialog", "Женский"))
        self.human_radio_btn.setText(_translate("Dialog", "Мужской"))
        self.theme_set.setText(_translate("Dialog", "     Тема:"))
        self.voice_set.setText(_translate("Dialog", "     Голос:"))
        self.white_set_btn.setText(_translate("Dialog", "Светлый"))
        self.black_set_btn.setText(_translate("Dialog", "Тёмный"))
        self.set_exit_btn.setText(_translate("Dialog", ""))
        self.confirm_btn.setText(_translate("Dialog", "Потвердить"))
        self.status_bar.setText(_translate("Dialog", "    "))
