# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'white_theme.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon
from PyQt5.QtCore import QSize
from style import start_btn_white_stl, setting_btn_white_stl, add_command_white_btn_stl, cls_btn_white_stl


class Ui_MainWindow_White(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(210, 153)
        MainWindow.setStyleSheet("background: #F0E9C5")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start_but = QtWidgets.QPushButton(self.centralwidget)
        self.start_but.setGeometry(QtCore.QRect(60, 20, 91, 71))
        self.start_but.setStyleSheet(start_btn_white_stl)
        self.start_but.setAutoDefault(False)
        self.start_but.setDefault(False)
        self.start_but.setObjectName("start_but")
        self.settings = QtWidgets.QPushButton(self.centralwidget)
        self.settings.setGeometry(QtCore.QRect(110, 110, 91, 31))
        self.settings.setStyleSheet(setting_btn_white_stl)
        self.settings.setObjectName("settings")
        self.add_command = QtWidgets.QPushButton(self.centralwidget)
        self.add_command.setGeometry(QtCore.QRect(10, 110, 91, 31))
        self.add_command.setStyleSheet(add_command_white_btn_stl)
        self.add_command.setObjectName("add_command")
        self.close_but = QtWidgets.QPushButton(self.centralwidget)
        self.close_but.setGeometry(QtCore.QRect(180, 10, 21, 23))
        self.close_but.setStyleSheet(cls_btn_white_stl)
        self.close_but.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.close_but.setObjectName("close_but")
        self.close_but.setIcon(QIcon('closer.png'))
        self.close_but.setIconSize(QSize(10, 10))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", " Louis - best assistant"))
        self.start_but.setText(_translate("MainWindow", "Запрос"))
        self.settings.setText(_translate("MainWindow", "Настройки"))
        self.add_command.setText(_translate("MainWindow", "Добавить команду"))
        self.close_but.setText(_translate("MainWindow", ""))
